# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ï—š](green)[ï—š](purple)[ï—š](red)[ï—š](yellow)[ï—š](blue)[ï—š](cyan)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](green)[âœ—](purple)[âœ—](red)[âœ—](yellow)[âœ—](blue)[âœ—](cyan)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = false

[hostname]
ssh_only = false
format = '[@](bold green)[$hostname]($style) '
style = 'bold blue'
disabled = false

[username]
format = '[\[](bold red)[$user]($style)'
style_user = 'bold yellow'
show_always = true

[git_branch]
symbol = "î‚  "
format = ' [$symbol$branch]($style) '
truncation_length = 4
truncation_symbol = ''
style = 'bold green'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_commit]
format = '[\\($hash\\)]($style) [\\($tag\\)]($style)'
commit_hash_length = 4
tag_symbol = 'ğŸ·'

[git_status]
format='([\[$all_status$ahead_behind\]]($style))'
conflicted = '='
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
untracked = '?'
stashed = '$'
modified = '!'
staged = '[++\($count\)](green)'
renamed = 'Â»'
deleted = 'âœ˜'
style = "bold purple"

[directory]
truncation_length = 8
truncation_symbol = 'â€¦/'
format = '[$path]($style)[$lock_symbol]($lock_style)[\]](bold red)'
style = 'bold red'
read_only = 'ğŸ”’'
read_only_style= 'bold white'

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = " took [$duration]($style)"
